on:
  schedule:
    - cron: '5 * * * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check the deployed service URL
      - uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-raad.onrender.com/health
